name: Build Docker Image

on:
  release:
    types:
      - published

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensure submodules are checked out

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3 python3-pip build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev libprotobuf-dev protobuf-compiler ccache

      - name: Build Project
        run: |
          ccache --max-size=150M
          ccache --set-config=compression=true
          cmake -S . -B build -D ARCH="default" -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Release
          cmake --build build -j3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t nyancod3r/monero_cli:${{ github.event.release.tag_name }} .
          docker tag nyancod3r/monero_cli:${{ github.event.release.tag_name }} nyancod3r/monero_cli:${{ github.sha }}
          inspect_output=$(docker inspect "nyancod3r/monero_cli:${{ github.event.release.tag_name }}")
          echo "Docker Inspect Output: $inspect_output"

      - name: Extract Hash from Logs
        run: |
          image_sha256=$(echo "$inspect_output" | jq -r '.[0].Id')
          echo "Image SHA256 Hash: $image_sha256" >> image_description.txt

      - name: Push Docker Image
        run: docker push nyancod3r/monero_cli:${{ github.event.release.tag_name }}

      - name: Update Release Description
        run: |
          release_id=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/nyancod3r/monero-to-docker/releases/tags/${{ github.event.release.tag_name }}" | jq -r '.id')
          current_description=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/nyancod3r/monero-to-docker/releases/$release_id" | jq -r '.body')

          # Append the SHA256 hash to the existing release description
          updated_description="${current_description}"$'\n'"$(cat image_description.txt)"

          # Update the release with the new description
          curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -X PATCH --data "{\"body\":\"${updated_description}\"}" "https://api.github.com/repos/nyancod3r/monero-to-docker/releases/$release_id"