name: Build Docker Image

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Build Docker Image
      run: |
        docker build -t nyancod3r/monero_cli:latest .
        docker tag  nyancod3r/monero_cli:latest  nyancod3r/monero_cli:${{ github.sha }}

    - name: Create SHA256 Hash
      run: |
        image_sha256=$(docker inspect --format='{{index .RepoDigests 0}}' "$(docker build -q .)")
        echo "Image SHA256 Hash: $image_sha256" >> image_description.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORDDOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker push  nyancod3r/monero_cli:latest
        docker push  nyancod3r/monero_cli:${{ github.sha }}
    
    - name: Update Release Description
      run: |
        release_id=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${GH_REPOSITORY}/releases/latest" | jq -r '.id')
        current_description=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${GH_REPOSITORY}/releases/$release_id" | jq -r '.body
        # Append the SHA256 hash to the existing release description
        updated_description="${current_description}"$'\n'"$(cat image_description.txt
        # Update the release with the new description
        curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -X PATCH --data "{\"body\":\"${updated_description}\"}" "https://api.github.com/repos/${GH_REPOSITORY}/releases/$release_id"